"""initial migration

Revision ID: ee7c04c2d66f
Revises: 
Create Date: 2025-07-25 21:53:44.279520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7c04c2d66f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserTable_id'), 'UserTable', ['id'], unique=False)
    op.create_index(op.f('ix_UserTable_name'), 'UserTable', ['name'], unique=False)
    op.create_index(op.f('ix_UserTable_username'), 'UserTable', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserTable_username'), table_name='UserTable')
    op.drop_index(op.f('ix_UserTable_name'), table_name='UserTable')
    op.drop_index(op.f('ix_UserTable_id'), table_name='UserTable')
    op.drop_table('UserTable')
    # ### end Alembic commands ###
